### ISSUE TITLE
Error when UTF (ü) character in filename?

### ISSUE THREAD

**Issue by rsgabriel** [kz26/dottorrent#3]
M:\path\Transcodes>"C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\python.exe" "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\Scripts\dottorrent_cli" --tracker http://tracker/announce --private "M:\path\Transcodes\Müzik" "M:\path\Transcodes\Müzik.torrent"

dottorrent/1.5.0 (https://github.com/kz26/dottorrent)
Input: M:\path\Transcodes\Teoman [2016] Iki Ask [Avrupa Müzik Yapim, WEB] [V2
]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\Scripts
\dottorrent_cli", line 85, in <module>
    t_info = t.get_info()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\dottorrent\__init__.py", line 155, in get_info
    raise exceptions.EmptyInputException
dottorrent.exceptions.EmptyInputException: Input path must be non-empty

**Comment by kz26** [comment]
I assume the input path `M:\path\Transcodes\Teoman [2016] Iki Ask [Avrupa Müzik Yapim, WEB] [V2
]` contains at least one non-empty file? Also, can you try updating dottorrent to the latest version (1.5.3) and let me know if the error still persists?

**Comment by kz26** [comment]
Closed due to non-activity.
